[workspace]
members = ["rush_core","calc_rule"]

[workspace.package]
edition = "2021"
authors = ["Teshin <1443965173@qq.com>"]
repository = "https://github.com/woshihaoren4/rush"
keywords = ["rush"]
description = "The rules engine is based on the rete algorithm"


[workspace.dependencies]
wd_tools = {version = "0.8.10",features = ["point-free","sync"]}
anyhow = "1.0.75"
serde = {version = "1.0.188",features = ["derive"]}
serde_json = "1.0.105"
nom = "7.1.3"